ports:
  - name: Dev Server
    description: Development server
    port: 3000
    onOpen: open-browser
    visibility: public

tasks:
  - name: Setup
    init: |
      npm install
      npm install -g @openai/codex
    command: |
      # Configure codex with the API key from Gitpod secrets
      codex set api-key $OPENAI_API_KEY
      gp sync-done install-complete
  
  - name: Codex
    command: |
      gp sync-await install-complete
      codex
    openMode: tab-after
      
  - name: Server
    command: |
      gp sync-await install-complete
      npm run dev