ports:
  - name: Dev Server
    description: Next.js development server
    port: 3000
    onOpen: open-browser
    visibility: public

tasks:
  - name: Setup and Dev Server
    command: |
      npm install
      npm install -g @openai/codex
      codex-cli config set api-key $OPENAI_API_KEY
      codex
      
  - name: Server
    command: |
     npm run dev
     