ports:
  - name: Dev Server
    description: Development server
    port: 3000
    onOpen: open-browser
    visibility: public

tasks:
  - name: Setup
    init: |
      npm install
      npm install -g @openai/codex
      gp sync-done install-complete
    command: |
      npm run dev
  
  - name: Codex
    command: |
      gp sync-await install-complete
      codex