ports:
  - name: Dev Server
    description: Next.js development server
    port: 3000
    onOpen: open-browser
    visibility: public

tasks:
  - name: Install and start dev server
    command: |
      npm install
      npm run dev